3-module-task
js-tasks-ru/jsbasic-20231211_alexandr-schegolkov pull request #4
Opened 2023-12-27 10:54 UTC by AlexanderSchegolkov

2023-12-27 10:54 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2023-12-27 11:29 UTC, koalex requested changes
Исправить замечания **3-1** и **3-2**

2023-12-27 11:29 UTC, koalex commented on 3-module/1-task/index.js
На занятии просил решить эту задачу методом [map](https://learn.javascript.ru/array-methods#map)

2023-12-27 11:29 UTC, koalex commented on 3-module/2-task/index.js
На занятии просил решить эту задачу методом [filter](https://learn.javascript.ru/array-methods#filter)

2023-12-27 18:48 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2023-12-28 02:46 UTC, koalex approved these changes
Отлично!

2023-12-28 02:46 UTC, koalex commented on 3-module/1-task/index.js
Отлично!

2023-12-28 02:46 UTC, merged