5-module-hometask
js-tasks-ru/jsbasic-20231211_alexandr-schegolkov pull request #5
Opened 2024-01-08 20:21 UTC by AlexanderSchegolkov

Здравствуйте, Константин! Катастрофически не хватает времени на выполнение всех заданий. Отравляю Вам на проверку задания 5 модуля (и 1 задание из 4). По тестам, вроде бы, всё хорошо, но слайдер-карусель работает не совсем корректно. При пролистывании слайдов с помощью правой стрелки, а затем дальнейшего возврата на первый слайд, правая стрелка перестает функционировать. Честно сказать, даже нет предположение, почему так получается. Подскажите, пожалуйста, как это можно исправить

2024-01-08 20:22 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2024-01-12 04:57 UTC, koalex requested changes
См. замечание по **5-3**

2024-01-12 04:57 UTC, koalex commented on 5-module/2-task/index.js
> +      text.hidden = true;
`text.hidden = !text.hidden;` [тут](https://discord.com/channels/920345781267996692/1172418207886352405/1194173071448363139) писал про это

2024-01-12 04:57 UTC, koalex commented on 5-module/3-task/index.js
Ширирну слайд надо считать в момент клика т.к. при инициализации карусель ещё может отсутствовать в DOM-дереве и ширина может равно 0. Я накидал решение с переписыванием, но без логики стрелок, попробуйте дописать его:
```function initCarousel() {
  let arrowLeft = document.querySelector(".carousel__arrow_left");
  let arrowRight = document.querySelector(".carousel__arrow_right");
  let carouselInner = document.querySelector(".carousel__inner");
  arrowLeft.style.display = "none";

  let counter = 0; //счётчик перелистаных слайдов 

  arrowRight.addEventListener("click", () => {
    counter++;
    carouselInner.style.transform = `translateX(-${carouselInner.offsetWidth * counter}px)`
    // Тут дописать логику стрелок
  });

  arrowLeft.addEventListener("click", () => {
    counter--;
    carouselInner.style.transform = `translateX(-${carouselInner.offsetWidth * counter}px)`
    // Тут дописать логику стрелок
  });
}```

2024-01-12 05:27 UTC, koalex requested changes
Исправить **5-3**

2024-01-12 09:55 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-01-13 05:26 UTC, koalex requested changes
Исправить **4-3**

2024-01-13 05:26 UTC, koalex commented on 5-module/2-task/index.js
> +    if (text.hidden != true) {
На занятии говорил и [писал в чате](https://discord.com/channels/920345781267996692/1172418207886352405/1194173071448363139):
`text.hidden = !text.hidden;`

2024-01-13 05:26 UTC, koalex commented on 4-module/3-task/index.js
> +  for (i = 1; i < 6; i++) {
В корне неверный подход. Почему 6? В таблице нет 6 строк, а может быть любое кол-во.

2024-01-13 05:26 UTC, koalex commented on 4-module/3-task/index.js
```
const FIRST_COLUMN = 1;
 const SECOND_COLUMN = 2;
 const THIRD_COLUMN = 3;

function highlight(table) {
   const actions = {
     [THIRD_COLUMN]: (root, td) => {
       if (td.dataset.available === 'true') {
         root.classList.toggle('available', true);
       } else if (td.dataset.available === 'false') {
         root.classList.toggle('unavailable', true);
       } else if (!td.hasAttribute('data-available')) {
         root.hidden = true;
       }
     },
     [SECOND_COLUMN]: (root, td) => {
       if (td.textContent === 'm') {
         root.classList.toggle('male', true);
       } else if (td.textContent === 'f') {
         root.classList.toggle('female', true);
       }
     },
     [FIRST_COLUMN]: (root, td) => {
       const age = parseInt(td.textContent, 10);

       if (age < 18) {
         root.style.textDecoration = 'line-through';
       }
     },
   };

   for (const tr of table.rows) {
     Array.from(tr.cells).forEach((td, index) => {
       const fn = actions[index];

       if (typeof fn === 'function') {
         fn(tr, td);
       }
     });
   }
}
```

2024-01-14 08:20 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2024-01-14 09:06 UTC, koalex approved these changes

2024-01-14 09:07 UTC, merged